### ISSUE TITLE
Kick, ban not working

### ISSUE THREAD

**Issue by sleepntsheep** [ronnapatp/kaoladbot#4]
![](https://file.papangkorn.com/FHgnYG/msedge_qKdHHLpzZy.png)

**Comment by ronnapatp** [comment]
There are some bug around the code but not worry we will fix it later

**Comment by ronnapatp** [comment]
That work na krub
![image](https://user-images.githubusercontent.com/84321166/136823030-fb5117e3-b293-4206-a861-d1e0265e2f30.png)
![image](https://user-images.githubusercontent.com/84321166/136823101-fe54b656-e093-4118-8b44-33aa110497b1.png)

**Comment by ronnapatp** [comment]
I think is a bug that can use only in one server per time of kick or ban Pls try again and tell me!!

**Comment by sleepntsheep** [comment]
It's still not working for me, weird 🤔.

**Comment by ronnapatp** [comment]
🤔
